//! WASM compilation via `cargo build` for scaffolded micro-crates.
//!
//! Given a scaffolded micro-crate directory (produced by [`super::scaffold`]),
//! this module invokes `cargo build --target wasm32-unknown-unknown --release`,
//! then post-processes the output with `wasm-bindgen` to produce JS glue and a
//! transformed WASM blob suitable for browser `import()`.

use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::Context;
use tokio::process::Command;

/// Full RUSTFLAGS for atomics/shared-memory WASM builds (rayon cells).
///
/// Required by wasm-bindgen-rayon: enables atomics target features AND linker
/// flags for shared memory, imported memory, and TLS exports so that the
/// resulting WASM module can be shared across Web Workers via `postMessage`.
const ATOMICS_RUSTFLAGS: &str = "\
    -C target-feature=+atomics,+bulk-memory,+mutable-globals \
    -C link-arg=--shared-memory \
    -C link-arg=--max-memory=2147483648 \
    -C link-arg=--import-memory \
    -C link-arg=--export=__wasm_init_tls \
    -C link-arg=--export=__tls_size \
    -C link-arg=--export=__tls_align \
    -C link-arg=--export=__tls_base";

/// Toolchain used for atomics/shared-memory (rayon) cell builds.
///
/// `-Zbuild-std` requires a nightly with the `rust-src` component. This is
/// **pinned** rather than a floating `+nightly` so the atomics build is
/// reproducible and cannot drift into breakage as the rolling nightly advances
/// — wasm-bindgen-rayon's `atomics` target-feature guard (`compile_error!`)
/// began failing on nightlies newer than this one. Keep in sync with
/// `rust-toolchain.toml`; the deploy image must install this toolchain with
/// `rust-src` and the `wasm32-unknown-unknown` target.
const ATOMICS_TOOLCHAIN: &str = "nightly-2025-12-22";

/// RUSTFLAGS enabling Enzyme autodiff (`std::autodiff`) for a cell build.
const AUTODIFF_RUSTFLAGS: &str = "-Zautodiff=Enable";

/// Toolchain used for `std::autodiff` (Enzyme) cell builds.
///
/// **Pinned**, for the same reason as [`ATOMICS_TOOLCHAIN`]: rolling nightlies
/// drift into breakage. The first deploy used the rolling `nightly` and the
/// 2026-07 nightly promptly ICE'd on cannon-notebook cells
/// (`rustc_middle/src/ty/typetree.rs: incorrect autodiff typetree handling
/// for slice`); this 2026-06-01 nightly is the one the feature was verified
/// end to end on. The `enzyme` rustup component exists for it (absent for the
/// atomics pin, 2025-12-22) and ships a matching libEnzyme/LLVM pair. The
/// deploy image and dev hosts must install this toolchain with the `enzyme`
/// and `rust-src` components and the wasm32 target. If both rayon and
/// autodiff are requested, this toolchain wins (it has rust-src for
/// `-Zbuild-std`).
const AUTODIFF_TOOLCHAIN: &str = "nightly-2026-06-01";

/// Hard timeout for a single `cargo build` invocation.
/// Override with `IRONPAD_BUILD_TIMEOUT_SECS` env var (default: 300s).
fn build_timeout() -> Duration {
    let secs = std::env::var("IRONPAD_BUILD_TIMEOUT_SECS")
        .ok()
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(300);
    Duration::from_secs(secs)
}

// ── Build Result ─────────────────────────────────────────────────────────────

/// Outcome of a micro-crate build attempt.
///
/// Infrastructure errors (spawn failure, timeout) are returned as `Err` from
/// [`build_micro_crate`].  Compilation success vs. failure is represented here
/// so the caller can inspect stdout (JSON diagnostics) in both cases.
pub enum BuildResult {
    /// Compilation succeeded; WASM blob and JS glue are on disk.
    Success {
        wasm_path: PathBuf,
        stdout: String,
        stderr: String,
        /// JS glue module generated by `wasm-bindgen` (`--target web`).
        js_glue: String,
    },
    /// Compilation failed (non-zero exit); stdout contains JSON diagnostics.
    Failure { stdout: String, stderr: String },
}

// ── Public API ───────────────────────────────────────────────────────────────

/// Build a scaffolded micro-crate to WASM.
///
/// Runs `cargo build --target wasm32-unknown-unknown --release
/// --message-format=json` in `crate_dir`, with:
///
/// * `CARGO_HOME` → shared registry cache under `cache_dir`
/// * `CARGO_TARGET_DIR` → per-session directory for incremental reuse
///
/// Returns [`BuildResult::Success`] with the `.wasm` blob path on success,
/// or [`BuildResult::Failure`] with raw cargo output on compilation failure.
///
/// # Errors
///
/// Returns `Err` for infrastructure problems: failed to spawn cargo, build
/// timeout exceeded, or missing `.wasm` artifact after a successful exit code.
#[allow(clippy::too_many_arguments)]
pub async fn build_micro_crate(
    crate_dir: &Path,
    cache_dir: &Path,
    session_id: &str,
    cell_id: &str,
    compilation_proxy: Option<&str>,
    needs_atomics: bool,
    needs_autodiff: bool,
) -> anyhow::Result<BuildResult> {
    let cargo_home = cargo_home_dir(cache_dir);
    let target_dir = if needs_atomics {
        atomics_target_dir(cache_dir)
    } else {
        target_dir(cache_dir, session_id)
    };

    tokio::fs::create_dir_all(&cargo_home).await?;
    tokio::fs::create_dir_all(&target_dir).await?;

    // Canonicalize paths so they resolve correctly when cargo runs in crate_dir.
    let cargo_home = tokio::fs::canonicalize(&cargo_home).await?;
    let target_dir = tokio::fs::canonicalize(&target_dir).await?;

    tracing::info!(
        cell_id = %cell_id,
        crate_dir = %crate_dir.display(),
        cargo_home = %cargo_home.display(),
        target_dir = %target_dir.display(),
        needs_atomics = needs_atomics,
        rustup_toolchain = %std::env::var("RUSTUP_TOOLCHAIN").unwrap_or_default(),
        "starting WASM build",
    );

    let timeout = build_timeout();

    let mut cmd = Command::new("cargo");
    configure_cargo_cmd(
        &mut cmd,
        "build",
        crate_dir,
        &cargo_home,
        &target_dir,
        compilation_proxy,
        needs_atomics,
        needs_autodiff,
    );
    cmd.stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        // Backstop: if the future is dropped, kill at least the direct child.
        .kill_on_drop(true);

    // Run cargo as its own process-group leader so a timeout can kill cargo AND
    // its rustc/build-script children in one killpg — killing only cargo leaves
    // a compile-bomb's children burning CPU/RAM.
    #[cfg(unix)]
    cmd.process_group(0);

    let child = cmd.spawn().map_err(|e| {
        tracing::error!(cell_id = %cell_id, error = %e, "failed to spawn cargo");
        anyhow::anyhow!("failed to spawn cargo: {e}")
    })?;
    let child_pid = child.id();

    let Ok(wait_result) = tokio::time::timeout(timeout, child.wait_with_output()).await else {
        // Timed out: kill the whole process group (cargo + rustc + build
        // scripts). The negated pgid equals cargo's pid because we made it the
        // group leader; SIGKILL can't be caught, so the tree dies.
        #[cfg(unix)]
        if let Some(pid) = child_pid.and_then(|p| i32::try_from(p).ok()) {
            // SAFETY: kill(2) with a negative pid signals the process group.
            unsafe {
                libc::kill(-pid, libc::SIGKILL);
            }
        }
        tracing::error!(cell_id = %cell_id, "cargo build timed out after {}s", timeout.as_secs());
        return Err(anyhow::anyhow!(
            "compilation timed out after {}s",
            timeout.as_secs()
        ));
    };
    let output = wait_result.map_err(|e| {
        tracing::error!(cell_id = %cell_id, error = %e, "cargo build failed to complete");
        anyhow::anyhow!("cargo build failed: {e}")
    })?;

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    if !output.status.success() {
        tracing::warn!(
            cell_id = %cell_id,
            exit_code = ?output.status.code(),
            stdout = %stdout,
            stderr = %stderr,
            "cargo build failed",
        );
        return Ok(BuildResult::Failure { stdout, stderr });
    }

    let wasm_path = expected_wasm_path(&target_dir, cell_id);

    anyhow::ensure!(
        wasm_path.exists(),
        "WASM blob not found at expected path: {}",
        wasm_path.display(),
    );

    tracing::info!(wasm_path = %wasm_path.display(), "WASM build succeeded, running wasm-bindgen");

    // Post-process with wasm-bindgen to generate JS glue + transformed WASM.
    let wasm_bindgen_out_dir = crate_dir.join("wasm-bindgen-out");
    std::fs::create_dir_all(&wasm_bindgen_out_dir)?;

    let wb_output = tokio::process::Command::new("wasm-bindgen")
        .arg("--target")
        .arg("web")
        .arg("--out-dir")
        .arg(&wasm_bindgen_out_dir)
        .arg("--no-typescript")
        .arg(&wasm_path)
        .output()
        .await
        .context("wasm-bindgen CLI not found. Install it with: cargo install wasm-bindgen-cli")?;

    if !wb_output.status.success() {
        let wb_stderr = String::from_utf8_lossy(&wb_output.stderr);
        anyhow::bail!("wasm-bindgen failed: {wb_stderr}");
    }

    // wasm-bindgen converts hyphens to underscores in output filenames.
    let cell_crate_name = format!("cell_{}", cell_id.replace('-', "_"));
    let js_glue_path = wasm_bindgen_out_dir.join(format!("{cell_crate_name}.js"));
    let bg_wasm_path = wasm_bindgen_out_dir.join(format!("{cell_crate_name}_bg.wasm"));

    let js_glue =
        std::fs::read_to_string(&js_glue_path).context("Failed to read wasm-bindgen JS glue")?;

    anyhow::ensure!(
        bg_wasm_path.exists(),
        "wasm-bindgen transformed WASM not found at: {}",
        bg_wasm_path.display(),
    );

    tracing::info!(
        js_glue_len = js_glue.len(),
        bg_wasm = %bg_wasm_path.display(),
        "wasm-bindgen post-processing succeeded",
    );

    Ok(BuildResult::Success {
        wasm_path: bg_wasm_path,
        stdout,
        stderr,
        js_glue,
    })
}

/// Apply the cargo invocation shared by [`build_micro_crate`] and
/// [`check_micro_crate`]: toolchain selection, the `{subcommand} --target
/// wasm32-unknown-unknown --release --message-format=json` args,
/// `CARGO_HOME`/`CARGO_TARGET_DIR`, host-flag scrubbing, the optional compile
/// proxy, and the atomics/shared-memory flags for rayon cells.
///
/// Extracting this keeps the build and check entry points from silently
/// drifting — e.g. an `env_remove` added later for correctness lands in both the
/// production build and the `cargo check` guard behind
/// `all_public_notebook_cells_compile`. Stdio/process-group setup stays with the
/// caller since only the real build needs it.
#[allow(clippy::too_many_arguments)]
fn configure_cargo_cmd(
    cmd: &mut Command,
    subcommand: &str,
    crate_dir: &Path,
    cargo_home: &Path,
    target_dir: &Path,
    compilation_proxy: Option<&str>,
    needs_atomics: bool,
    needs_autodiff: bool,
) {
    if needs_autodiff {
        cmd.arg(format!("+{AUTODIFF_TOOLCHAIN}"));
        cmd.env_remove("RUSTUP_TOOLCHAIN");
    } else if needs_atomics {
        cmd.arg(format!("+{ATOMICS_TOOLCHAIN}"));
        // Ensure the rustup shim respects our +toolchain over any inherited
        // override (e.g. RUSTUP_TOOLCHAIN set by the parent process).
        cmd.env_remove("RUSTUP_TOOLCHAIN");
    }

    cmd.arg(subcommand)
        .arg("--target")
        .arg("wasm32-unknown-unknown")
        .arg("--release")
        .arg("--message-format=json")
        .current_dir(crate_dir)
        .env("CARGO_HOME", cargo_home)
        .env("CARGO_TARGET_DIR", target_dir)
        // Clear host-target flags that may leak from the parent process
        // (e.g. cargo-leptos setting RUSTFLAGS with `-fuse-ld=mold`).
        .env_remove("RUSTFLAGS")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .env_remove("CARGO_BUILD_RUSTFLAGS");

    if let Some(proxy) = compilation_proxy {
        cmd.env("HTTPS_PROXY", proxy);
        cmd.env("HTTP_PROXY", proxy);
    }

    // Compose RUSTFLAGS: atomics and autodiff can coexist (both are plain
    // flag sets; the autodiff toolchain carries rust-src for -Zbuild-std).
    let mut rustflags = Vec::new();
    if needs_atomics {
        cmd.arg("-Zbuild-std=std,panic_abort");
        rustflags.push(ATOMICS_RUSTFLAGS);
    }
    if needs_autodiff {
        rustflags.push(AUTODIFF_RUSTFLAGS);
    }
    if !rustflags.is_empty() {
        cmd.env("RUSTFLAGS", rustflags.join(" "));
    }
}

/// Check (type-check only) a scaffolded micro-crate without full codegen.
///
/// Runs `cargo check --target wasm32-unknown-unknown --release
/// --message-format=json`.  Much faster than [`build_micro_crate`] because it
/// skips LLVM codegen, WASM linking, and wasm-bindgen post-processing.
///
/// Intended for bulk validation (e.g. checking every public notebook cell).
#[cfg(test)]
pub async fn check_micro_crate(
    crate_dir: &Path,
    cache_dir: &Path,
    session_id: &str,
    _cell_id: &str,
    compilation_proxy: Option<&str>,
    needs_atomics: bool,
    needs_autodiff: bool,
) -> anyhow::Result<CheckResult> {
    let cargo_home = cargo_home_dir(cache_dir);
    let target_dir = if needs_atomics {
        atomics_target_dir(cache_dir)
    } else {
        target_dir(cache_dir, session_id)
    };

    std::fs::create_dir_all(&cargo_home)?;
    std::fs::create_dir_all(&target_dir)?;

    let cargo_home = std::fs::canonicalize(&cargo_home)?;
    let target_dir = std::fs::canonicalize(&target_dir)?;

    let timeout = build_timeout();
    let output = tokio::time::timeout(timeout, {
        let mut cmd = Command::new("cargo");
        configure_cargo_cmd(
            &mut cmd,
            "check",
            crate_dir,
            &cargo_home,
            &target_dir,
            compilation_proxy,
            needs_atomics,
            needs_autodiff,
        );
        cmd.output()
    })
    .await
    .map_err(|_| anyhow::anyhow!("cargo check timed out after {}s", timeout.as_secs()))?
    .map_err(|e| anyhow::anyhow!("failed to spawn cargo: {e}"))?;

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    if output.status.success() {
        Ok(CheckResult::Ok)
    } else {
        Ok(CheckResult::Failure { stdout, stderr })
    }
}

/// Outcome of a `cargo check` invocation.
#[cfg(test)]
pub enum CheckResult {
    /// Type-checking passed.
    Ok,
    /// Compilation errors; stdout has JSON diagnostics, stderr has human-readable output.
    Failure { stdout: String, stderr: String },
}

// ── Path Helpers ─────────────────────────────────────────────────────────────

/// Shared `CARGO_HOME` directory for registry caching across all builds.
pub fn cargo_home_dir(cache_dir: &Path) -> PathBuf {
    cache_dir.join("cargo-home")
}

/// Per-session `CARGO_TARGET_DIR` for incremental build reuse.
pub fn target_dir(cache_dir: &Path, session_id: &str) -> PathBuf {
    cache_dir.join("targets").join(session_id)
}

/// Shared target directory for atomics-enabled builds.
///
/// All rayon cells share this directory so they benefit from a pre-built
/// std sysroot with atomics support.
pub fn atomics_target_dir(cache_dir: &Path) -> PathBuf {
    cache_dir.join("targets").join("atomics-shared")
}

/// Compute the expected path to the compiled `.wasm` blob.
///
/// Cargo converts crate-name hyphens to underscores in artifact filenames.
/// The scaffolded crate name is `cell-{cell_id}` (see [`super::scaffold`]).
pub fn expected_wasm_path(target_dir: &Path, cell_id: &str) -> PathBuf {
    let crate_name = format!("cell-{cell_id}");
    let wasm_filename = format!("{}.wasm", crate_name.replace('-', "_"));

    target_dir
        .join("wasm32-unknown-unknown")
        .join("release")
        .join(wasm_filename)
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── cargo_home_dir ──────────────────────────────────────────────────

    #[test]
    fn cargo_home_under_cache() {
        let dir = cargo_home_dir(Path::new("/cache"));
        assert_eq!(dir, PathBuf::from("/cache/cargo-home"));
    }

    // ── target_dir ──────────────────────────────────────────────────────

    #[test]
    fn target_dir_per_session() {
        let dir = target_dir(Path::new("/cache"), "session-1");
        assert_eq!(dir, PathBuf::from("/cache/targets/session-1"));
    }

    #[test]
    fn target_dir_different_sessions_are_isolated() {
        let a = target_dir(Path::new("/cache"), "sess-a");
        let b = target_dir(Path::new("/cache"), "sess-b");
        assert_ne!(a, b);
    }

    // ── atomics_target_dir ──────────────────────────────────────────────

    #[test]
    fn atomics_target_dir_is_shared() {
        let dir = atomics_target_dir(Path::new("/cache"));
        assert_eq!(dir, PathBuf::from("/cache/targets/atomics-shared"));
    }

    // ── expected_wasm_path ──────────────────────────────────────────────

    #[test]
    fn wasm_path_simple_id() {
        let path = expected_wasm_path(Path::new("/t"), "abc123");
        assert_eq!(
            path,
            PathBuf::from("/t/wasm32-unknown-unknown/release/cell_abc123.wasm"),
        );
    }

    #[test]
    fn wasm_path_hyphenated_id() {
        let path = expected_wasm_path(Path::new("/t"), "cell-0");
        assert_eq!(
            path,
            PathBuf::from("/t/wasm32-unknown-unknown/release/cell_cell_0.wasm"),
        );
    }

    #[test]
    fn wasm_path_nested_hyphens() {
        let path = expected_wasm_path(Path::new("/t"), "a-b-c");
        assert_eq!(
            path,
            PathBuf::from("/t/wasm32-unknown-unknown/release/cell_a_b_c.wasm"),
        );
    }

    #[test]
    fn wasm_path_underscore_id() {
        let path = expected_wasm_path(Path::new("/t"), "my_cell");
        assert_eq!(
            path,
            PathBuf::from("/t/wasm32-unknown-unknown/release/cell_my_cell.wasm"),
        );
    }
}
