//! Shared types for the ironpad compilation pipeline, notebook persistence, and UI.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ── Compilation Types ────────────────────────────────────────────────────────

/// Request sent from the client to compile a single cell.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CompileRequest {
    pub notebook_id: String,
    pub cell_id: String,
    pub source: String,
    pub cargo_toml: String,
    /// Type tags from all previous cells, used to generate typed input bindings.
    /// Empty string means the cell has no type tag (display-only output).
    #[serde(default)]
    pub previous_cell_types: Vec<String>,
    /// Notebook-level shared Cargo.toml whose dependencies are merged with per-cell deps.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_cargo_toml: Option<String>,
    /// Notebook-level shared Rust source included as `src/shared.rs` in every cell micro-crate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_source: Option<String>,
    /// What kind of cell this is (PRD-0066). The server derives the compile
    /// target from it through `CellTarget::from`, which is the one mapping
    /// from what a cell IS to what it builds for.
    ///
    /// `#[serde(default)]` is load-bearing for wire compatibility: a request
    /// from a client that predates this field still deserializes, as `Code`,
    /// which is exactly what such a client meant. Without it every older
    /// browser tab would start failing to compile anything at all.
    #[serde(default)]
    pub cell_type: CellType,
    /// When `true`, bypass the compilation cache and force a fresh build.
    #[serde(default)]
    pub force: bool,
    /// Live-check target inside `shared.rs` (PRD-0046). When set, `check_cell`
    /// validates the assembled shared source (the cell body is a throwaway)
    /// and returns only diagnostics anchored inside this line range, remapped
    /// to cell-local lines. Ignored by `compile_cell`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_check: Option<SharedCheckRange>,
}

/// The slice of the assembled `shared.rs` occupied by one shared cell, as
/// computed by [`shared_cell_line_offset`] plus the cell's own line count.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SharedCheckRange {
    /// 0-based line at which the cell's source begins in the assembly.
    pub start_line: u32,
    /// Number of lines the cell's source occupies.
    pub line_count: u32,
}

/// Response from the server after a compilation attempt.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CompileResponse {
    /// The compiled WASM blob (empty on failure).
    pub wasm_blob: Vec<u8>,
    /// Compiler diagnostics (errors, warnings, notes).
    pub diagnostics: Vec<Diagnostic>,
    /// Whether the result was served from cache.
    pub cached: bool,
    /// Number of scaffold preamble lines for diagnostic line-number adjustment.
    #[serde(default)]
    pub preamble_lines: u32,
    /// JS glue module generated by `wasm-bindgen` (ES module source).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub js_glue: Option<String>,
}

/// A single compiler diagnostic (error, warning, or note).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Diagnostic {
    pub message: String,
    pub severity: Severity,
    pub spans: Vec<Span>,
    /// Optional Rust error code (e.g. `"E0308"`), used for linking to the
    /// [Rust error index](https://doc.rust-lang.org/error_codes/).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

/// Severity level for a compiler diagnostic.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
    Note,
}

/// A source-code span associated with a diagnostic.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Span {
    pub line_start: u32,
    pub line_end: u32,
    pub col_start: u32,
    pub col_end: u32,
    pub label: Option<String>,
}

// ── Execution Result Types ───────────────────────────────────────────────────

/// Result of executing a compiled WASM cell.
///
/// Populated by the executor bridge after `cell_main` runs; rendered by the
/// editor's output panel and the view-only pages, and its `output_bytes`
/// feed downstream cells as typed inputs.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ExecutionResult {
    /// JSON-serialized `Vec<DisplayPanel>` from the cell's output panels.
    /// Parse with `serde_json::from_str` on the frontend. Falls back to a single
    /// Text panel if parsing fails (backward compatibility).
    pub display_text: Option<String>,
    /// Raw output bytes (bincode-serialized payload for the next cell).
    pub output_bytes: Vec<u8>,
    /// Wall-clock execution time in milliseconds.
    pub execution_time_ms: f64,
    /// Rust type tag of the cell output (e.g. `"u32"`, `"String"`, `"Vec<i32>"`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub type_tag: Option<String>,
    /// `true` when execution fell back to the main thread (e.g. because a
    /// DOM-dependent library like plotters panicked in the Web Worker).
    #[serde(default)]
    pub ran_on_main_thread: bool,
}

// ── Live check (PRD-0045) ────────────────────────────────────────────────────

/// Outcome bucket for a live `cargo check` of a cell.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum CheckStatus {
    /// Type-checked clean (no error diagnostics).
    Clean,
    /// Check completed with diagnostics.
    Errors,
    /// Skipped: the cell's compile lock was busy (a build/check in flight).
    Skipped,
    /// Exceeded the live-check time budget (expected for cold caches).
    TimedOut,
}

/// Response for the live check-on-type server fn. Diagnostics are already
/// preamble-adjusted to user-source coordinates, same as compile responses.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CheckResponse {
    pub status: CheckStatus,
    pub diagnostics: Vec<Diagnostic>,
}

/// True when the merged manifests declare any dependency beyond
/// `ironpad-cell` — the static half of the live-check warmth policy
/// (PRD-0045): the image warmup pre-checks the ironpad-cell tree, so a cell
/// with no custom deps is warm by construction, while custom deps mean the
/// first check would pay a full dependency build and must wait for a
/// successful compile instead.
///
/// Delegates to [`crate::cache_key::has_user_dependencies`] — the SAME
/// dotted-aware parser the scaffold merge uses — so the inline and dotted
/// `[dependencies.NAME]` forms are understood identically. A hand-rolled
/// line scan here once missed the dotted form and mis-classified such a cell
/// as warm, dispatching a cold check on every keystroke.
#[must_use]
pub fn manifest_has_custom_deps(shared_cargo_toml: Option<&str>, cell_cargo_toml: &str) -> bool {
    shared_cargo_toml.is_some_and(crate::cache_key::has_user_dependencies)
        || crate::cache_key::has_user_dependencies(cell_cargo_toml)
}

// ── Cell Type ────────────────────────────────────────────────────────────────

/// What a cell *is*, which decides how it compiles and where it runs.
///
/// `Code` and `Linux` are both compiled Rust and are otherwise nothing alike:
/// a `Code` cell is a fragment wrapped into `cell_main`, compiled to
/// `wasm32-unknown-unknown` and called by our executor through a dozen host
/// functions; a `Linux` cell is a whole program with its own `fn main`,
/// compiled to `wasm32-browserpod-linux-musl` and run as a real process under
/// an in-browser kernel that services 431 syscalls (PRD-0066).
///
/// `Unsupported` is the forward-compatibility arm and the reason this enum
/// carries `#[serde(other)]`. A client that meets a cell type from a newer
/// release must render it inert rather than guess: PRD-0047 shipped a live bug
/// where an old cached client treated shared cells as ordinary ones and
/// compiled them, and silently mistaking a `Linux` cell for `Code` would
/// compile a whole program to the wrong target and fail incomprehensibly.
/// Deserializing to `Unsupported` also keeps ONE unknown cell from failing the
/// whole notebook parse, so the rest of the document still opens.
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Default, PartialEq, Eq)]
pub enum CellType {
    #[default]
    Code,
    Markdown,
    /// A whole Rust program run as a Linux process in the browser (PRD-0066).
    Linux,
    /// Any cell type this build does not know. Never written, only read.
    #[serde(other)]
    Unsupported,
}

impl CellType {
    /// Whether this cell compiles Rust at all. Markdown does not, and an
    /// `Unsupported` cell must not, since we cannot know what it meant.
    #[must_use]
    pub fn compiles(self) -> bool {
        matches!(self, Self::Code | Self::Linux)
    }

    /// Whether this cell runs under `BrowserPod` rather than our own executor.
    #[must_use]
    pub fn is_linux(self) -> bool {
        matches!(self, Self::Linux)
    }
}

// ── Cell Manifest ────────────────────────────────────────────────────────────

/// A single cell entry within a notebook manifest.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CellManifest {
    pub id: String,
    pub order: u32,
    pub label: String,
    /// Cell type — `Code` (default) or `Markdown`. Missing field deserializes as `Code`
    /// for backward compatibility with existing notebooks.
    #[serde(default)]
    pub cell_type: CellType,
    /// Shared cell (PRD-0044); surfaces the flag to manifest consumers (CLI).
    #[serde(default)]
    pub shared: bool,
    /// Saved default-collapse state for the code body (mirrors
    /// [`IronpadCell::collapsed`]) so the editor's cell list can mount cells
    /// in their load state.
    #[serde(default)]
    pub collapsed: bool,
    /// Saved default-collapse state for the output panel (mirrors
    /// [`IronpadCell::output_collapsed`]).
    #[serde(default)]
    pub output_collapsed: bool,
}

impl CellManifest {
    /// Whether Run All executes this cell: a Code cell that is not shared
    /// (shared cells never execute — their source rides in every other
    /// cell's `shared.rs`). The single definition of "runnable".
    #[must_use]
    pub fn is_runnable(&self) -> bool {
        self.cell_type == CellType::Code && !self.shared
    }
}

// ── Self-contained Notebook Types ───────────────────────────────────────────

/// A complete, self-contained notebook with embedded cell content.
///
/// Carries everything needed to render or fork a notebook
/// in a single value. Used for `IndexedDB` storage and view-only/shared pages.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct IronpadNotebook {
    pub version: u32,
    pub id: Uuid,
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_cargo_toml: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_source: Option<String>,
    /// When `true`, editing a cell auto-re-executes downstream cells after a debounce.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reactive_mode: Option<bool>,
    /// Root-relative path to a hand-made social-preview image, overriding the
    /// card the server generates from this notebook's metadata.
    ///
    /// The generated card is text: title, description, and a code excerpt. A
    /// notebook whose whole point is a picture (a fractal, a raymarched scene)
    /// is better represented by a real screenshot, and this is how it says so.
    /// Root-relative only, so a notebook can never point a crawler at an
    /// arbitrary third-party origin under ironpad's name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub og_image: Option<String>,
    /// Pixel size of [`og_image`](Self::og_image), declared to unfurlers.
    ///
    /// Only meaningful alongside an override: the generated card is always
    /// 1200x630 and says so from a constant. An override of any other shape
    /// still advertised 1200x630 before these existed, and unfurlers lay the
    /// preview out from the *declared* size, so a tall screenshot came out
    /// letterboxed or cropped. Read them through
    /// [`og_image_dimensions`](Self::og_image_dimensions), never directly.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub og_image_width: Option<u32>,
    /// See [`og_image_width`](Self::og_image_width).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub og_image_height: Option<u32>,
    // NOTE: a notebook-level `expand_code: Option<bool>` used to live here.
    // Collapse state is per-cell now (`IronpadCell::collapsed`), WYSIWYG from
    // the editor; old JSON carrying the field still parses (serde ignores
    // unknown fields).
    pub cells: Vec<IronpadCell>,
}

/// Smallest edge length an `og_image` override may declare. Most unfurlers
/// discard a card below roughly 200px rather than showing a tiny one.
pub const OG_IMAGE_MIN_PX: u32 = 200;

/// Largest edge length an `og_image` override may declare. Well above any real
/// screenshot; the point is that a declared 100000px reserves a layout box in
/// someone's feed before the image itself is ever fetched.
pub const OG_IMAGE_MAX_PX: u32 = 8192;

/// Generated OG-card dimensions. 1200x630 is the size every major unfurler
/// asks for (Reddit, X, Slack, Discord, `LinkedIn` all converge on it); a
/// smaller image gets demoted to a thumbnail beside the title. ONE source:
/// the server rasterizes the card at this size (`ironpad_server::og::svg`)
/// and the client advertises it via `og:image:width/height`
/// (`social_meta`) — two constants would let the rendered card and the
/// announced size drift, and unfurlers lay out against the announced one.
pub const OG_CARD_WIDTH: u32 = 1200;
/// Generated OG-card height. See [`OG_CARD_WIDTH`].
pub const OG_CARD_HEIGHT: u32 = 630;

/// Route prefix for immutable content-addressed share blobs (PRD-0047). ONE
/// source for the client fetch URL ([`share_blob_url`]), the axum route
/// registration, and the immutable-cache prefix check — a drift here breaks
/// blob delivery silently (viewers fall back to live compilation).
pub const SHARE_BLOBS_PREFIX: &str = "/share-blobs/";

/// Client-side URL for a snapshotted share blob. `glue` selects the
/// wasm-bindgen JS glue (`.js`) over the wasm module (`.wasm`); both share
/// the `{blob}.{ext}` scheme with the server's on-disk filenames.
#[must_use]
pub fn share_blob_url(blob: &str, glue: bool) -> String {
    format!(
        "{SHARE_BLOBS_PREFIX}{blob}.{}",
        if glue { "js" } else { "wasm" }
    )
}

/// Default shared `Cargo.toml` for new notebooks. Provides `ironpad-cell`
/// and relaxed release-profile settings so cells compile quickly.
pub const DEFAULT_SHARED_CARGO_TOML: &str = "\
[dependencies]\n\
ironpad-cell = \"0.1\"\n\
\n\
[profile.release]\n\
opt-level = 1\n\
lto = false\n\
codegen-units = 16\n";

/// Per-cell budget for a saved output payload (PRD-0056). Inside the 4 MiB
/// notebook cap with headroom; an over-budget output degrades to
/// [`SAVED_OUTPUT_TOO_LARGE`] rather than failing the share.
pub const SAVED_OUTPUT_BUDGET_BYTES: usize = 256 * 1024;

/// The placeholder panels JSON substituted for an over-budget saved output.
/// Shaped as a real `Text` panel so the viewer renders it through the normal
/// panel path with no special casing.
pub const SAVED_OUTPUT_TOO_LARGE: &str =
    r#"[{"Text":"(output too large to embed; run the cell to regenerate it)"}]"#;

impl IronpadNotebook {
    /// Embed each cell's last-run output panels (PRD-0056), from the
    /// editor's `cell_display_texts` capture, honoring the per-cell budget.
    ///
    /// Called at serialize time only (Share, Push's durable save, Download):
    /// the editor's in-memory model and the debounced draft autosaves stay
    /// lean. Cells with no recorded output keep `None`; a cell whose payload
    /// exceeds `per_cell_budget` gets [`SAVED_OUTPUT_TOO_LARGE`] instead.
    pub fn embed_saved_outputs(
        &mut self,
        display_texts: &std::collections::HashMap<String, String>,
        per_cell_budget: usize,
    ) {
        for cell in &mut self.cells {
            if let Some(panels) = display_texts.get(&cell.id) {
                cell.saved_output = Some(if panels.len() <= per_cell_budget {
                    panels.clone()
                } else {
                    SAVED_OUTPUT_TOO_LARGE.to_string()
                });
            }
            // No fresh capture for this cell: KEEP any prior snapshot that
            // traveled with the notebook. The /mutable editor after its
            // hard navigation is the concrete case — the session never ran
            // the cell, and assigning `None` here stripped the published
            // snapshot on the very next Push (caught by the push-path e2e).
        }
    }

    /// Creates a new empty notebook with the given title.
    pub fn new(title: &str) -> Self {
        let now = Utc::now();
        Self {
            version: 1,
            id: Uuid::new_v4(),
            title: title.to_string(),
            description: None,
            tags: None,
            created_at: now,
            updated_at: now,
            shared_cargo_toml: Some(DEFAULT_SHARED_CARGO_TOML.to_string()),
            shared_source: None,
            reactive_mode: None,
            og_image: None,
            og_image_width: None,
            og_image_height: None,
            cells: Vec::new(),
        }
    }

    /// The social-preview image this notebook declares, if it declares a
    /// usable one.
    ///
    /// Enforces the root-relative rule at the single point of use rather than
    /// trusting the field: notebooks arrive from shares and from `IndexedDB`,
    /// so the value is attacker-controlled, and an `og:image` pointing at
    /// another origin would let a shared notebook borrow ironpad's name for
    /// whatever it liked in someone else's feed. A protocol-relative `//host`
    /// is rejected for the same reason, since crawlers resolve it as absolute.
    #[must_use]
    pub fn og_image_path(&self) -> Option<&str> {
        let raw = self.og_image.as_deref()?.trim();
        (raw.starts_with('/') && !raw.starts_with("//")).then_some(raw)
    }

    /// Whether two copies of this notebook carry the same content.
    ///
    /// Ignores `updated_at`, which the storage layer bumps on *every* save
    /// (pushed or not), so raw equality between a local working copy and the
    /// published copy of a mutable share would report a difference that no
    /// reader could see. Everything else — including future fields, via the
    /// `PartialEq` derive — participates.
    #[must_use]
    pub fn content_matches(&self, other: &Self) -> bool {
        let mut other = other.clone();
        other.updated_at = self.updated_at;
        *self == other
    }

    /// The declared size of this notebook's override image, if it declares a
    /// usable one.
    ///
    /// Gated at the point of use for the same reason as
    /// [`og_image_path`](Self::og_image_path): the numbers arrive from shares
    /// and from `IndexedDB`, so they are attacker-controlled. Three conditions,
    /// each of which has a failure mode behind it.
    ///
    /// Both dimensions must be present, because a preview laid out from one
    /// axis and a stale constant on the other is worse than no declaration at
    /// all. They must be within [`OG_IMAGE_MIN_PX`]..=[`OG_IMAGE_MAX_PX`],
    /// because most unfurlers reject a card below roughly 200px and a declared
    /// 100000px reserves a viewport-breaking box before the image ever loads.
    /// And there must be an override image at all: dimensions without one would
    /// mislabel the generated card, which is always 1200x630.
    #[must_use]
    pub fn og_image_dimensions(&self) -> Option<(u32, u32)> {
        self.og_image_path()?;
        let (w, h) = (self.og_image_width?, self.og_image_height?);
        let ok = |px: u32| (OG_IMAGE_MIN_PX..=OG_IMAGE_MAX_PX).contains(&px);
        (ok(w) && ok(h)).then_some((w, h))
    }

    /// The shared source the compiler should see: the notebook-level
    /// `shared_source` followed by every shared cell's source, in notebook
    /// order. See [`effective_shared_source`].
    #[must_use]
    pub fn effective_shared_source(&self) -> Option<String> {
        effective_shared_source(self.shared_source.as_deref(), &self.cells)
    }
}

/// Assemble the shared source for compilation: the notebook-level shared
/// source first, then the source of every `shared` cell in notebook order,
/// separated by blank lines.
///
/// This is the single definition of how shared cells fold into `shared.rs` —
/// the browser (editor and view-only paths) and the public-notebook check
/// gate must all call it, or validation drifts from production. Returns
/// `None` when there is no shared content at all, preserving the
/// `Option<String>` shape the compile pipeline keys its cache on
/// (`None` and `Some("")` hash differently on purpose).
///
/// Rust item order is compilation-irrelevant, so cell order only affects the
/// readability of the generated `shared.rs`.
#[must_use]
pub fn effective_shared_source(
    notebook_shared: Option<&str>,
    cells: &[IronpadCell],
) -> Option<String> {
    let parts = shared_parts(notebook_shared, cells);
    if parts.is_empty() {
        None
    } else {
        Some(
            parts
                .iter()
                .map(|(_, src)| *src)
                .collect::<Vec<_>>()
                .join("\n\n"),
        )
    }
}

/// The ordered pieces of the shared assembly: the notebook-level source (no
/// cell id) followed by each shared cell's `(id, source)` in `order`. Both
/// [`effective_shared_source`] and [`shared_cell_line_offset`] derive from
/// this one list, so the join and the line math can never disagree.
fn shared_parts<'a>(
    notebook_shared: Option<&'a str>,
    cells: &'a [IronpadCell],
) -> Vec<(Option<&'a str>, &'a str)> {
    let mut cells_by_order: Vec<&IronpadCell> = cells.iter().filter(|c| c.shared).collect();
    cells_by_order.sort_by_key(|c| c.order);

    let mut parts: Vec<(Option<&str>, &str)> = Vec::with_capacity(cells_by_order.len() + 1);
    if let Some(s) = notebook_shared {
        parts.push((None, s));
    }
    parts.extend(
        cells_by_order
            .iter()
            .map(|c| (Some(c.id.as_str()), c.source.as_str())),
    );
    parts
}

/// The 0-based line at which `target_id`'s source begins inside
/// [`effective_shared_source`]'s output, or `None` when the cell is absent or
/// not shared. Each earlier part contributes its own lines plus the one blank
/// separator line from the `"\n\n"` join.
#[must_use]
pub fn shared_cell_line_offset(
    notebook_shared: Option<&str>,
    cells: &[IronpadCell],
    target_id: &str,
) -> Option<u32> {
    let mut line = 0u32;
    for (cell_id, src) in shared_parts(notebook_shared, cells) {
        if cell_id == Some(target_id) {
            return Some(line);
        }
        line += u32::try_from(src.split('\n').count()).unwrap_or(u32::MAX) + 1;
    }
    None
}

/// A single cell within an [`IronpadNotebook`], including its source code.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct IronpadCell {
    pub id: String,
    pub order: u32,
    pub label: String,
    #[serde(default)]
    pub cell_type: CellType,
    pub source: String,
    /// Per-cell `Cargo.toml` content. `None` for Markdown cells.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cargo_toml: Option<String>,
    /// Shared cell: its source is appended to the notebook's `shared.rs`
    /// (after the notebook-level shared source) instead of executing. Shared
    /// cells render highlighted, have no run button and no output, and exist
    /// so a notebook can narrate the load-bearing parts of its shared code
    /// inline instead of hiding them in one collapsed blob (PRD-0044).
    /// Defaults to `false` so every pre-existing notebook parses unchanged.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub shared: bool,
    /// Code body starts collapsed. WYSIWYG: the collapse state the author
    /// leaves a cell in while editing is the state every surface (edit mode,
    /// view mode, public/shared/embed pages) loads it in. Defaults to `false`
    /// (open) so existing notebooks parse unchanged.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub collapsed: bool,
    /// Output panel starts collapsed. Same WYSIWYG semantics as `collapsed`.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub output_collapsed: bool,
    /// Optimistic concurrency control version. Incremented on each mutation.
    /// Defaults to 0 for backward compatibility with existing notebooks.
    #[serde(default)]
    pub version: u64,
    /// Saved output panels JSON from the author's last run (PRD-0056),
    /// embedded at the editorial moments (Share, Push's durable save,
    /// Download) so view-only pages render a finished document before any
    /// compile. Display-only — piping bytes are never persisted — and set
    /// only by [`IronpadNotebook::embed_saved_outputs`] at serialize time,
    /// never by the editor's model or the wire protocol's mutations.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub saved_output: Option<String>,
}

impl IronpadCell {
    /// Whether Run All executes this cell — see [`CellManifest::is_runnable`].
    #[must_use]
    pub fn is_runnable(&self) -> bool {
        self.cell_type == CellType::Code && !self.shared
    }
}

// ── Share Blob Manifest (PRD-0047) ──────────────────────────────────────────

/// One snapshotted cell artifact in a share: the content hash naming the
/// `.wasm` (and optional `.js` glue) files under `/share-blobs/`.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ShareBlobEntry {
    /// 64-hex blake3 content hash; the blob is served as `/share-blobs/{blob}.wasm`.
    pub blob: String,
    /// Whether a wasm-bindgen JS glue sibling (`/share-blobs/{blob}.js`) exists.
    pub has_js_glue: bool,
}

/// Sidecar manifest written next to a shared notebook at share time, mapping
/// cell ids to their snapshotted compiled artifacts. Viewers with a manifest
/// entry fetch the immutable blob instead of invoking `compile_cell`; cells
/// without an entry (or any fetch failure) fall back to the live pipeline.
///
/// Stored at `{data_dir}/shares/{share_hash}.manifest.json`, deliberately
/// separate from the `{share_hash}.json` notebook so the stored notebook
/// format (and existing shares) stay untouched.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ShareManifest {
    /// Manifest schema version (currently 1).
    pub version: u32,
    /// Cell id → snapshotted artifact. `BTreeMap` for stable serialization.
    pub cells: std::collections::BTreeMap<String, ShareBlobEntry>,
}

// ── Public Notebook Types ───────────────────────────────────────────────────

/// Lightweight summary of a public notebook for the home-page listing.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PublicNotebookSummary {
    pub id: String,
    pub title: String,
    pub description: String,
    pub filename: String,
    pub cell_count: usize,
    #[serde(default)]
    pub tags: Vec<String>,
}

// ── Mutable Share Types (PRD-0049) ──────────────────────────────────────────

/// Lightweight summary of one server-stored notebook owned by the caller,
/// for the home-page account listing and the "find everything on a fresh
/// machine" flow. Enumerated server-side from the caller's OWNER grants.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct MutableShareSummary {
    /// Server-minted share id (the `/mutable/{id}` path segment).
    pub id: String,
    pub title: String,
    /// Whether a reader-visible published copy exists (PRD-0064). An
    /// account notebook that has never been published is 404 to everyone
    /// but its owner, so the listing is the only place it appears.
    #[serde(default)]
    pub published: bool,
    /// ISO 8601 timestamp of the last push. `None` until the first publish.
    #[serde(default)]
    pub pushed_at: Option<String>,
    /// ISO 8601 timestamp the notebook entered the account.
    #[serde(default)]
    pub created_at: String,
    pub cell_count: usize,
    /// The notebook's tags, so the home search matches an account notebook
    /// on a tag exactly as it matches a local or public one.
    #[serde(default)]
    pub tags: Vec<String>,
}

/// The timestamp an account-notebook listing dates and orders by: the last
/// publish, else creation. Ordering on `pushed_at` alone would sink every
/// unpublished notebook below every published one (PRD-0064).
///
/// ONE home for the rule, deliberately. The server sorts owned rows by it
/// and the home page dates cards by it, off two different structs, and a
/// listing sorted by one definition while dated by another is a bug nobody
/// would think to look for. Anything carrying an optional publish timestamp
/// and a creation timestamp calls this rather than re-deriving it.
#[must_use]
pub fn last_activity<'a>(pushed_at: Option<&'a str>, created_at: &'a str) -> &'a str {
    pushed_at.unwrap_or(created_at)
}

impl MutableShareSummary {
    /// See [`last_activity`]: this is that one rule, applied to this struct's
    /// fields. It holds no rule of its own.
    #[must_use]
    pub fn last_activity(&self) -> &str {
        last_activity(self.pushed_at.as_deref(), &self.created_at)
    }
}

// ── Accounts Types (PRD-0053) ───────────────────────────────────────────────

/// The signed-in user as exposed to the client. Deliberately excludes the
/// GitHub id — the client never needs it, and identity checks happen
/// server-side against the session cookie.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct CurrentUser {
    pub login: String,
    /// May be empty (test users); the UI renders an initial-letter fallback.
    pub avatar_url: String,
}

/// Auth surface state for the client: whether sign-in exists on this
/// deployment at all (OAuth env configured), and who is signed in.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct AuthInfo {
    /// False when the server has no GitHub OAuth credentials — the sign-in
    /// button is hidden and the instance runs anonymous-only.
    pub enabled: bool,
    pub user: Option<CurrentUser>,
}

/// Owner attribution for a mutable share's reader page.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ShareOwner {
    pub login: String,
    pub avatar_url: String,
}

/// Reader-page payload for a mutable share: the notebook, its owner
/// attribution, and whether the CALLER's session holds the OWNER grant.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct MutableNotebookResponse {
    pub notebook: IronpadNotebook,
    pub owner: Option<ShareOwner>,
    pub is_owner: bool,
}

/// The reader path's three-way outcome for a mutable share (PRD-0061).
///
/// `Private` is deliberately distinct from `NotFound`: a private link handed
/// to the right person must render a sign-in prompt that WORKS after one
/// sign-in, not dead-end on a 404. Content never rides the `Private` arm.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub enum MutableNotebookAccess {
    Found(Box<MutableNotebookResponse>),
    /// The share exists but the caller (anonymous, or signed in without a
    /// grant) may not view it. `signed_in` picks the denial copy.
    Private {
        signed_in: bool,
    },
    NotFound,
}

/// One READ grant on a private share, for the owner's Access UI (PRD-0061).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ShareGrant {
    pub github_id: String,
    pub login: String,
    pub avatar_url: String,
}

/// The owner's access view of a share (PRD-0061): the privacy flag plus the
/// current READ grants, fetched together when the Access UI mounts.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ShareAccess {
    pub private: bool,
    pub grants: Vec<ShareGrant>,
}

/// The owner's editing payload for a mutable share (PRD-0054): the server
/// draft when one exists (else the published copy), and whether they differ
/// (which is what arms the Push button on load).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct MutableEditResponse {
    pub notebook: IronpadNotebook,
    pub dirty: bool,
    /// Whether a published copy exists (PRD-0064). `dirty` cannot tell an
    /// unpublished notebook from a published one with pending edits — the
    /// first is permanently dirty by construction — and the toolbar says
    /// Publish for one and Push for the other.
    #[serde(default)]
    pub published: bool,
    /// The share's privacy flag (PRD-0061). Serde default keeps pre-0061
    /// clients decoding.
    #[serde(default)]
    pub private: bool,
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Compile-request wire contract (PRD-0066) ────────────────────────

    /// A compile request from a client that predates `cell_type` must still
    /// deserialize, as `Code`.
    ///
    /// The pkg bundle is content-hashed and served immutable, so a browser
    /// tab loaded before a deploy keeps posting the old JSON shape for as
    /// long as it stays open. Without the `#[serde(default)]` that tab stops
    /// compiling anything at all — and PRD-0047 already shipped one live bug
    /// of exactly this family (a stale client silently mis-handling a newer
    /// notebook field).
    #[test]
    fn a_compile_request_without_a_cell_type_is_a_code_cell() {
        let json = r#"{
            "notebook_id": "nb",
            "cell_id": "c1",
            "source": "40 + 2",
            "cargo_toml": "[dependencies]"
        }"#;
        let request: CompileRequest =
            serde_json::from_str(json).expect("a pre-0066 request must still parse");
        assert_eq!(request.cell_type, CellType::Code);

        // And the target that request selects is the ordinary one, which is
        // what makes every cached blob from before this field still valid.
        assert_eq!(
            crate::cache_key::CellTarget::from(request.cell_type),
            crate::cache_key::CellTarget::Executor,
        );
    }

    /// A Linux cell round-trips as `Linux`, and an unknown cell type from a
    /// FUTURE release lands on `Unsupported` rather than being guessed at.
    #[test]
    fn a_compile_request_carries_its_cell_type_over_the_wire() {
        let request = CompileRequest {
            notebook_id: "nb".to_string(),
            cell_id: "c1".to_string(),
            source: "fn main() {}".to_string(),
            cargo_toml: String::new(),
            cell_type: CellType::Linux,
            previous_cell_types: vec![],
            shared_cargo_toml: None,
            shared_source: None,
            force: false,
            shared_check: None,
        };
        let round_tripped: CompileRequest =
            serde_json::from_str(&serde_json::to_string(&request).unwrap()).unwrap();
        assert_eq!(round_tripped.cell_type, CellType::Linux);
        assert_eq!(
            crate::cache_key::CellTarget::from(round_tripped.cell_type),
            crate::cache_key::CellTarget::Linux,
        );

        // A type this build has never heard of must not be compiled as if it
        // were `Code`: it deserializes inert.
        let future = serde_json::to_string(&request)
            .unwrap()
            .replace("\"Linux\"", "\"Quantum\"");
        let future: CompileRequest = serde_json::from_str(&future).unwrap();
        assert_eq!(future.cell_type, CellType::Unsupported);
        assert!(!future.cell_type.compiles());
    }

    // ── Account-notebook listing wire contract (PRD-0064) ───────────────

    /// One rule, applied off two structs. The method must hold no rule of
    /// its own, or the server's sort and the home page's date can disagree.
    #[test]
    fn last_activity_is_publish_then_creation() {
        assert_eq!(
            last_activity(Some("2026-08-12"), "2026-08-01"),
            "2026-08-12"
        );
        assert_eq!(last_activity(None, "2026-08-01"), "2026-08-01");

        let mut s = MutableShareSummary {
            id: "abcdef0123456789".into(),
            title: "Account Notebook".into(),
            published: false,
            pushed_at: None,
            created_at: "2026-08-01T00:00:00Z".into(),
            cell_count: 3,
            tags: vec![],
        };
        assert_eq!(s.last_activity(), s.created_at);
        assert_eq!(
            s.last_activity(),
            last_activity(s.pushed_at.as_deref(), &s.created_at)
        );

        s.published = true;
        s.pushed_at = Some("2026-08-12T00:00:00Z".into());
        assert_eq!(s.last_activity(), s.pushed_at.as_deref().unwrap());
        assert_eq!(
            s.last_activity(),
            last_activity(s.pushed_at.as_deref(), &s.created_at)
        );
    }

    /// `serde(default)` covers a MISSING field, never a null one, and the
    /// two halves of that sentence have opposite consequences here.
    ///
    /// Decoding is tolerant in the direction that matters for a stale
    /// cached bundle reading a payload it predates: absent `published`,
    /// `created_at` and `tags` all decode.
    ///
    /// Encoding is NOT: an unpublished notebook puts an explicit
    /// `"pushed_at": null` on the wire, which a client compiled against the
    /// pre-0064 `String` rejects, failing the WHOLE `Vec` rather than one
    /// row. That is pinned here so widening the field again is a deliberate
    /// act; the shell's `?v={release}` cache-buster is what keeps a stale
    /// bundle from seeing it, and `home_page.rs` logs the decode failure so
    /// the empty group is diagnosable if one ever does.
    #[test]
    fn summary_decodes_a_pre_0064_payload_but_encodes_an_explicit_null() {
        let legacy = r#"{
            "id": "abcdef0123456789",
            "title": "Published Before 0064",
            "pushed_at": "2026-07-01T00:00:00Z",
            "cell_count": 4
        }"#;
        let s: MutableShareSummary =
            serde_json::from_str(legacy).expect("pre-0064 payload decodes");
        assert_eq!(s.pushed_at.as_deref(), Some("2026-07-01T00:00:00Z"));
        assert!(!s.published, "absent flag defaults to unpublished");
        assert!(s.created_at.is_empty());
        assert!(s.tags.is_empty());
        // Still dates correctly off the one field a pre-0064 row carried.
        assert_eq!(s.last_activity(), "2026-07-01T00:00:00Z");

        let unpublished = MutableShareSummary {
            id: "abcdef0123456789".into(),
            title: "Never Published".into(),
            published: false,
            pushed_at: None,
            created_at: "2026-08-01T00:00:00Z".into(),
            cell_count: 1,
            tags: vec!["wip".into()],
        };
        let wire = serde_json::to_string(&unpublished).unwrap();
        assert!(
            wire.contains("\"pushed_at\":null"),
            "None is an explicit null on the wire, not an omission: {wire}"
        );
        assert_eq!(
            serde_json::from_str::<MutableShareSummary>(&wire).unwrap(),
            unpublished
        );
    }

    #[test]
    fn manifest_custom_deps_classification() {
        // The static half of the live-check warmth policy (PRD-0045).
        assert!(!manifest_has_custom_deps(None, "[dependencies]"));
        assert!(!manifest_has_custom_deps(None, ""));
        assert!(!manifest_has_custom_deps(
            Some(DEFAULT_SHARED_CARGO_TOML),
            "[dependencies]\n# serde = \"1\" (commented out)",
        ));
        assert!(!manifest_has_custom_deps(
            None,
            "[dependencies]\nironpad-cell = { path = \"x\" }",
        ));
        assert!(manifest_has_custom_deps(
            None,
            "[dependencies]\nserde_json = \"1\"",
        ));
        assert!(manifest_has_custom_deps(
            Some("[dependencies]\nrayon = \"1\""),
            "[dependencies]",
        ));
        // Deps outside a [dependencies] section don't count.
        assert!(!manifest_has_custom_deps(
            None,
            "[profile.release]\nopt-level = 1",
        ));
        // Dotted `[dependencies.NAME]` subtables DO count — the build
        // pipeline supports them, so the warmth gate must see them too
        // (previously a hand-rolled line scan missed the form and
        // dispatched a cold check on every keystroke).
        assert!(manifest_has_custom_deps(
            None,
            "[dependencies.tokio]\nversion = \"1\"\nfeatures = [\"rt\"]",
        ));
        assert!(manifest_has_custom_deps(
            Some("[dependencies.rayon]\nversion = \"1\""),
            "",
        ));
        // ...but a dotted ironpad-cell subtable is still filtered.
        assert!(!manifest_has_custom_deps(
            None,
            "[dependencies.ironpad-cell]\npath = \"x\"",
        ));
    }

    #[test]
    fn content_matches_ignores_updated_at_but_not_content() {
        // The divergence check behind the mutable reader's author banner:
        // storage bumps updated_at on every save, so it must not count as a
        // difference — while any real edit must.
        let base = IronpadNotebook::new("t");

        let mut resaved = base.clone();
        resaved.updated_at += chrono::Duration::seconds(90);
        assert!(base.content_matches(&resaved));
        assert!(resaved.content_matches(&base));

        let mut retitled = base.clone();
        retitled.title = "t2".to_string();
        assert!(!base.content_matches(&retitled));

        let mut cell_added = base.clone();
        cell_added.cells.push(IronpadCell {
            id: "c1".to_string(),
            order: 0,
            label: "Cell 1".to_string(),
            cell_type: CellType::Code,
            source: "1 + 1".to_string(),
            cargo_toml: None,
            shared: false,
            collapsed: false,
            output_collapsed: false,
            version: 0,
            saved_output: None,
        });
        assert!(!base.content_matches(&cell_added));
    }

    #[test]
    fn og_image_path_admits_only_root_relative_paths() {
        let with = |v: Option<&str>| {
            let mut nb = IronpadNotebook::new("t");
            nb.og_image = v.map(str::to_string);
            nb
        };

        assert_eq!(
            with(Some("/og-custom/mandelbrot.png")).og_image_path(),
            Some("/og-custom/mandelbrot.png")
        );
        assert_eq!(with(None).og_image_path(), None);

        // A shared notebook is attacker-controlled content: none of these may
        // become the `og:image` a crawler attributes to ironpad.
        for hostile in [
            "https://evil.example/x.png",
            "//evil.example/x.png",
            "og-custom/relative.png",
            "javascript:alert(1)",
            "",
        ] {
            assert_eq!(
                with(Some(hostile)).og_image_path(),
                None,
                "should have rejected {hostile:?}"
            );
        }
    }

    #[test]
    fn notebook_without_og_image_field_round_trips() {
        let json = r#"{"version":1,"id":"00000000-0000-0000-0000-000000000000",
            "title":"t","created_at":"2026-01-01T00:00:00Z",
            "updated_at":"2026-01-01T00:00:00Z","cells":[]}"#;
        let nb: IronpadNotebook = serde_json::from_str(json).unwrap();
        assert_eq!(nb.og_image, None);
        assert_eq!(nb.og_image_width, None);
        assert_eq!(nb.og_image_height, None);
        // Absent stays absent on the way out, so adding this field does not
        // rewrite every stored notebook the first time it is re-saved.
        assert!(!serde_json::to_string(&nb).unwrap().contains("og_image"));
    }

    #[test]
    fn og_image_dimensions_require_a_usable_override_and_both_axes() {
        let with = |image: Option<&str>, w: Option<u32>, h: Option<u32>| {
            let mut nb = IronpadNotebook::new("t");
            nb.og_image = image.map(str::to_string);
            nb.og_image_width = w;
            nb.og_image_height = h;
            nb
        };
        let good = Some("/og-custom/mandelbrot.png");

        assert_eq!(
            with(good, Some(1024), Some(1024)).og_image_dimensions(),
            Some((1024, 1024))
        );

        // One axis alone would be laid out against the stale 1200x630
        // constant on the other, which is worse than declaring nothing.
        assert_eq!(with(good, Some(1024), None).og_image_dimensions(), None);
        assert_eq!(with(good, None, Some(1024)).og_image_dimensions(), None);

        // Dimensions with no override, or with a rejected one, would mislabel
        // the generated card, which is always 1200x630.
        assert_eq!(with(None, Some(800), Some(800)).og_image_dimensions(), None);
        assert_eq!(
            with(Some("https://evil.example/x.png"), Some(800), Some(800)).og_image_dimensions(),
            None
        );
    }

    #[test]
    fn og_image_dimensions_reject_implausible_pixel_counts() {
        let with = |w: u32, h: u32| {
            let mut nb = IronpadNotebook::new("t");
            nb.og_image = Some("/og-custom/x.png".to_string());
            nb.og_image_width = Some(w);
            nb.og_image_height = Some(h);
            nb
        };

        assert!(with(OG_IMAGE_MIN_PX, OG_IMAGE_MIN_PX)
            .og_image_dimensions()
            .is_some());
        assert!(with(OG_IMAGE_MAX_PX, OG_IMAGE_MAX_PX)
            .og_image_dimensions()
            .is_some());

        // A declared size reserves a layout box in someone's feed before the
        // image is fetched, so these are bounded rather than trusted.
        for (w, h) in [
            (0, 630),
            (1200, 0),
            (OG_IMAGE_MIN_PX - 1, 630),
            (OG_IMAGE_MAX_PX + 1, 630),
            (1200, u32::MAX),
        ] {
            assert_eq!(
                with(w, h).og_image_dimensions(),
                None,
                "should have rejected {w}x{h}"
            );
        }
    }

    #[test]
    fn cell_without_shared_field_defaults_to_false() {
        let json = r#"{"id": "c", "order": 0, "label": "c", "source": "1"}"#;
        let cell: IronpadCell = serde_json::from_str(json).unwrap();
        assert!(!cell.shared);
    }

    #[test]
    fn effective_shared_source_combines_notebook_and_cells_in_order() {
        let mk = |id: &str, order: u32, shared: bool, src: &str| IronpadCell {
            id: id.into(),
            order,
            label: id.into(),
            cell_type: CellType::Code,
            source: src.into(),
            cargo_toml: None,
            shared,
            collapsed: false,
            output_collapsed: false,
            version: 0,
            saved_output: None,
        };
        // Out-of-order Vec on purpose: assembly must follow `order`, not
        // Vec position.
        let cells = vec![
            mk("b", 3, true, "fn b() {}"),
            mk("x", 1, false, "let x = 1;"),
            mk("a", 2, true, "fn a() {}"),
        ];

        assert_eq!(
            effective_shared_source(Some("fn base() {}"), &cells).as_deref(),
            Some("fn base() {}\n\nfn a() {}\n\nfn b() {}"),
        );
        assert_eq!(
            effective_shared_source(None, &cells).as_deref(),
            Some("fn a() {}\n\nfn b() {}"),
        );
        assert_eq!(effective_shared_source(None, &cells[1..2]), None);
        // None vs Some("") must stay distinct — the cache hashes them apart.
        assert_eq!(
            effective_shared_source(Some(""), &cells[1..2]).as_deref(),
            Some(""),
        );
    }

    #[test]
    fn shared_cell_line_offset_matches_the_assembly() {
        let mk = |id: &str, order: u32, shared: bool, src: &str| IronpadCell {
            id: id.into(),
            order,
            label: id.into(),
            cell_type: CellType::Code,
            source: src.into(),
            cargo_toml: None,
            shared,
            collapsed: false,
            output_collapsed: false,
            version: 0,
            saved_output: None,
        };
        // Multi-line sources, out-of-order Vec: offsets must follow `order`.
        let cells = vec![
            mk("late", 5, true, "fn late() {\n    3\n}"),
            mk("plain", 1, false, "let x = 1;"),
            mk("early", 2, true, "fn early() {}\nfn early2() {}"),
        ];
        let base = "// base\nfn base() {}"; // 2 lines

        // With notebook-level source: base(2) + blank(1) = 3.
        assert_eq!(
            shared_cell_line_offset(Some(base), &cells, "early"),
            Some(3)
        );
        // early(2) + blank(1) after that = 6.
        assert_eq!(shared_cell_line_offset(Some(base), &cells, "late"), Some(6));

        // Without notebook-level source the first shared cell starts at 0.
        assert_eq!(shared_cell_line_offset(None, &cells, "early"), Some(0));
        assert_eq!(shared_cell_line_offset(None, &cells, "late"), Some(3));

        // Non-shared or unknown cells have no slice in the assembly.
        assert_eq!(shared_cell_line_offset(Some(base), &cells, "plain"), None);
        assert_eq!(shared_cell_line_offset(Some(base), &cells, "nope"), None);

        // The offsets must agree with the actual join: the target's source
        // starts exactly at the computed line of the assembled text.
        let assembled = effective_shared_source(Some(base), &cells).unwrap();
        let lines: Vec<&str> = assembled.split('\n').collect();
        let early_at = shared_cell_line_offset(Some(base), &cells, "early").unwrap() as usize;
        assert_eq!(lines[early_at], "fn early() {}");
        let late_at = shared_cell_line_offset(Some(base), &cells, "late").unwrap() as usize;
        assert_eq!(lines[late_at], "fn late() {");
    }

    #[test]
    fn cell_without_version_field_defaults_to_zero() {
        // Simulates loading a notebook saved before the version field existed.
        let json = r#"{
            "id": "cell-1",
            "order": 0,
            "label": "Cell 1",
            "source": "42"
        }"#;
        let cell: IronpadCell = serde_json::from_str(json).unwrap();
        assert_eq!(cell.version, 0);
    }

    #[test]
    fn embed_saved_outputs_sets_skips_and_budgets() {
        let mut nb = IronpadNotebook::new("t");
        nb.cells = vec![
            IronpadCell {
                id: "ran".into(),
                order: 0,
                label: "ran".into(),
                cell_type: CellType::Code,
                source: "42".into(),
                cargo_toml: None,
                shared: false,
                collapsed: false,
                output_collapsed: false,
                version: 0,
                saved_output: None,
            },
            IronpadCell {
                id: "cold".into(),
                order: 1,
                label: "cold".into(),
                cell_type: CellType::Code,
                source: "43".into(),
                cargo_toml: None,
                shared: false,
                collapsed: false,
                output_collapsed: false,
                version: 0,
                saved_output: None,
            },
            IronpadCell {
                id: "huge".into(),
                order: 2,
                label: "huge".into(),
                cell_type: CellType::Code,
                source: "44".into(),
                cargo_toml: None,
                shared: false,
                collapsed: false,
                output_collapsed: false,
                version: 0,
                saved_output: None,
            },
        ];
        let mut texts = std::collections::HashMap::new();
        texts.insert("ran".to_string(), r#"[{"Text":"42"}]"#.to_string());
        texts.insert(
            "huge".to_string(),
            "x".repeat(SAVED_OUTPUT_BUDGET_BYTES + 1),
        );

        nb.embed_saved_outputs(&texts, SAVED_OUTPUT_BUDGET_BYTES);

        assert_eq!(
            nb.cells[0].saved_output.as_deref(),
            Some(r#"[{"Text":"42"}]"#)
        );
        assert_eq!(
            nb.cells[1].saved_output, None,
            "never-captured cells stay empty"
        );
        assert_eq!(
            nb.cells[2].saved_output.as_deref(),
            Some(SAVED_OUTPUT_TOO_LARGE),
            "over-budget outputs degrade to the placeholder, never fail"
        );
        // The placeholder itself is valid panels JSON (a Text panel).
        assert!(SAVED_OUTPUT_TOO_LARGE.starts_with("[{\"Text\":"));

        // A prior snapshot survives a session that never ran the cell (the
        // /mutable editor after a hard navigation): re-embedding with no
        // fresh capture must PRESERVE, not strip.
        nb.cells[1].saved_output = Some(r#"[{"Text":"prior"}]"#.to_string());
        nb.embed_saved_outputs(&std::collections::HashMap::new(), SAVED_OUTPUT_BUDGET_BYTES);
        assert_eq!(
            nb.cells[1].saved_output.as_deref(),
            Some(r#"[{"Text":"prior"}]"#),
            "no capture preserves the prior snapshot"
        );
        assert_eq!(
            nb.cells[0].saved_output.as_deref(),
            Some(r#"[{"Text":"42"}]"#),
            "earlier fresh capture also survives"
        );
    }

    #[test]
    fn saved_output_round_trips_and_stays_lean_when_absent() {
        let mut nb = IronpadNotebook::new("t");
        nb.cells = vec![IronpadCell {
            id: "a".into(),
            order: 0,
            label: "a".into(),
            cell_type: CellType::Code,
            source: "42".into(),
            cargo_toml: None,
            shared: false,
            collapsed: false,
            output_collapsed: false,
            version: 0,
            saved_output: Some(r#"[{"Text":"42"}]"#.into()),
        }];
        let json = serde_json::to_string(&nb).unwrap();
        let back: IronpadNotebook = serde_json::from_str(&json).unwrap();
        assert_eq!(
            back.cells[0].saved_output.as_deref(),
            Some(r#"[{"Text":"42"}]"#)
        );

        // Absent field: parses (pre-0056 notebooks) and serializes away
        // (lean drafts stay byte-identical to before).
        let lean: IronpadNotebook = serde_json::from_str(
            &json.replace(",\"saved_output\":\"[{\\\"Text\\\":\\\"42\\\"}]\"", ""),
        )
        .unwrap();
        assert_eq!(lean.cells[0].saved_output, None);
        assert!(!serde_json::to_string(&lean)
            .unwrap()
            .contains("saved_output"));
    }

    #[test]
    fn cell_with_version_field_round_trips() {
        let cell = IronpadCell {
            id: "cell-1".into(),
            order: 0,
            label: "Cell 1".into(),
            cell_type: CellType::Code,
            source: "42".into(),
            cargo_toml: None,
            shared: false,
            collapsed: false,
            output_collapsed: false,
            version: 7,
            saved_output: None,
        };
        let json = serde_json::to_string(&cell).unwrap();
        let back: IronpadCell = serde_json::from_str(&json).unwrap();
        assert_eq!(back.version, 7);
    }

    #[test]
    fn cell_version_zero_is_serialized() {
        let cell = IronpadCell {
            id: "cell-1".into(),
            order: 0,
            label: "Cell 1".into(),
            cell_type: CellType::Code,
            source: "42".into(),
            cargo_toml: None,
            shared: false,
            collapsed: false,
            output_collapsed: false,
            version: 0,
            saved_output: None,
        };
        let json = serde_json::to_string(&cell).unwrap();
        // version:0 should be present (not skipped).
        assert!(json.contains("\"version\":0"));
    }

    // ── reactive_mode field ────────────────────────────────────────────

    #[test]
    fn notebook_without_reactive_mode_defaults_to_none() {
        let json = r#"{
            "version": 1,
            "id": "00000000-0000-0000-0000-000000000001",
            "title": "Test",
            "created_at": "2025-01-01T00:00:00Z",
            "updated_at": "2025-01-01T00:00:00Z",
            "cells": []
        }"#;
        let nb: IronpadNotebook = serde_json::from_str(json).unwrap();
        assert_eq!(nb.reactive_mode, None);
    }

    #[test]
    fn notebook_with_reactive_mode_true_round_trips() {
        let mut nb = IronpadNotebook::new("Reactive");
        nb.reactive_mode = Some(true);
        let json = serde_json::to_string(&nb).unwrap();
        assert!(json.contains("\"reactive_mode\":true"));
        let back: IronpadNotebook = serde_json::from_str(&json).unwrap();
        assert_eq!(back.reactive_mode, Some(true));
    }

    #[test]
    fn notebook_with_reactive_mode_false_round_trips() {
        let mut nb = IronpadNotebook::new("Non-Reactive");
        nb.reactive_mode = Some(false);
        let json = serde_json::to_string(&nb).unwrap();
        assert!(json.contains("\"reactive_mode\":false"));
        let back: IronpadNotebook = serde_json::from_str(&json).unwrap();
        assert_eq!(back.reactive_mode, Some(false));
    }

    #[test]
    fn notebook_reactive_mode_none_is_omitted_from_json() {
        let nb = IronpadNotebook::new("Default");
        let json = serde_json::to_string(&nb).unwrap();
        assert!(
            !json.contains("reactive_mode"),
            "reactive_mode=None should be skipped"
        );
    }

    // ── per-cell collapse flags ────────────────────────────────────────

    #[test]
    fn cell_collapse_flags_default_open_and_are_omitted_from_json() {
        // Old cell JSON (no flags) parses as open, and open cells serialize
        // without the fields — existing notebooks are byte-identical.
        let json = r#"{
            "id": "cell-1",
            "order": 0,
            "label": "Cell",
            "cell_type": "Code",
            "source": "42"
        }"#;
        let cell: IronpadCell = serde_json::from_str(json).unwrap();
        assert!(!cell.collapsed);
        assert!(!cell.output_collapsed);

        let out = serde_json::to_string(&cell).unwrap();
        assert!(!out.contains("collapsed"), "false flags should be skipped");
    }

    #[test]
    fn cell_collapse_flags_round_trip_when_set() {
        let mut cell: IronpadCell = serde_json::from_str(
            r#"{"id":"c","order":0,"label":"L","cell_type":"Code","source":"42"}"#,
        )
        .unwrap();
        cell.collapsed = true;
        cell.output_collapsed = true;
        let json = serde_json::to_string(&cell).unwrap();
        assert!(json.contains("\"collapsed\":true"));
        assert!(json.contains("\"output_collapsed\":true"));
        let back: IronpadCell = serde_json::from_str(&json).unwrap();
        assert!(back.collapsed);
        assert!(back.output_collapsed);
    }

    #[test]
    fn notebook_with_legacy_expand_code_field_still_parses() {
        // The notebook-level expand_code setting was replaced by per-cell
        // collapse state; old JSON carrying it must keep parsing (serde
        // ignores unknown fields) and the field simply drops on re-save.
        let json = r#"{
            "version": 1,
            "id": "00000000-0000-0000-0000-000000000001",
            "title": "Legacy",
            "created_at": "2025-01-01T00:00:00Z",
            "updated_at": "2025-01-01T00:00:00Z",
            "expand_code": true,
            "cells": []
        }"#;
        let nb: IronpadNotebook = serde_json::from_str(json).unwrap();
        let out = serde_json::to_string(&nb).unwrap();
        assert!(!out.contains("expand_code"));
    }

    #[test]
    fn notebook_new_defaults_reactive_mode_to_none() {
        let nb = IronpadNotebook::new("Fresh");
        assert_eq!(nb.reactive_mode, None);
    }

    /// Verify every `.ironpad` file in `public/notebooks/` deserializes as a
    /// valid [`IronpadNotebook`] and that each cell satisfies basic invariants.
    ///
    /// This catches missing/mistyped fields early — before they reach the
    /// server's `get_public_notebook` endpoint and produce a runtime error.
    #[test]
    fn all_public_notebooks_conform_to_schema() {
        let workspace_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .expect("could not locate workspace root");
        let notebooks_dir = workspace_root.join("public").join("notebooks");

        // ── Validate each .ironpad file ──────────────────────────────
        let mut count = 0;
        for entry in std::fs::read_dir(&notebooks_dir).expect("cannot read notebooks dir") {
            let entry = entry.expect("bad dir entry");
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("ironpad") {
                continue;
            }
            let filename = path.file_name().unwrap().to_string_lossy().to_string();

            let bytes =
                std::fs::read(&path).unwrap_or_else(|e| panic!("cannot read {filename}: {e}"));
            let nb: IronpadNotebook = serde_json::from_slice(&bytes)
                .unwrap_or_else(|e| panic!("{filename}: schema error: {e}"));

            // version must be 1.
            assert_eq!(
                nb.version, 1,
                "{filename}: unexpected version {}",
                nb.version
            );

            // Must have at least one cell.
            assert!(!nb.cells.is_empty(), "{filename}: no cells");

            // Public notebooks must have a description.
            assert!(
                nb.description.is_some(),
                "{filename}: missing description field"
            );

            // Cell order values must be sequential starting at 0.
            for (i, cell) in nb.cells.iter().enumerate() {
                assert_eq!(
                    cell.order,
                    u32::try_from(i).expect("too many cells"),
                    "{filename}: cell[{i}] order is {} but expected {i}",
                    cell.order
                );
                assert!(!cell.id.is_empty(), "{filename}: cell[{i}] has empty id");
                assert!(
                    !cell.label.is_empty(),
                    "{filename}: cell[{i}] has empty label"
                );
                assert!(
                    !cell.source.is_empty(),
                    "{filename}: cell[{i}] has empty source"
                );
            }

            count += 1;
        }

        // Sanity: we validated at least one notebook.
        assert!(
            count > 0,
            "no .ironpad files found in {}",
            notebooks_dir.display()
        );
    }
}

// ── Admin panel (PRD-0063) ──────────────────────────────────────────────────

/// One cache tier's name and current size, for the admin overview.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq)]
pub struct CacheTierUsage {
    /// The tier itself, so an action can name it without a round trip through
    /// a string the server would have to re-validate.
    pub tier: CacheTier,
    /// Directory name under the cache root, e.g. `targets`.
    pub name: String,
    pub bytes: u64,
    /// Whether the unattended boot-time pressure valve is allowed to clear it.
    /// `blobs` is not: losing compiled output turns every later page view into
    /// a cold compile.
    pub valve_may_clear: bool,
}

/// Instance state for the admin overview.
///
/// Read live from the filesystem and the database on every request; nothing
/// here is cached, so the numbers are only as fresh as the page.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq)]
pub struct AdminOverview {
    pub users: u64,
    pub sessions: u64,
    pub mutable_shares: u64,
    pub cache_tiers: Vec<CacheTierUsage>,
    /// Bytes under the accounts database directory, write-ahead log included.
    pub database_bytes: u64,
}

/// One user in the admin panel's list (PRD-0063).
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq)]
pub struct AdminUser {
    /// GitHub's numeric id as a string, and the handle for actions. Stable
    /// across a login rename, which the login itself is not.
    pub github_id: String,
    pub login: String,
    pub avatar_url: String,
    pub created_at: String,
    pub sessions: u64,
    pub owned_shares: u64,
}

// ── Cache tiers (PRD-0063) ──────────────────────────────────────────────────

/// One directory under the cache root.
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum CacheTier {
    /// cargo target dirs for cell builds. The largest tier by far (3.2GB in
    /// production) and pure derived state.
    Targets,
    /// Scaffolded micro-crates. Rebuilt per compile.
    Workspaces,
    /// The shared cargo registry. Rebuildable, but re-downloading it makes
    /// every first compile slow, so the valve only reaches for it under
    /// sustained pressure.
    CargoHome,
    /// Compiled cell blobs, keyed by content hash. **Not rebuildable without
    /// recompiling**, and what stands between a reader and a cold compile, so
    /// the automatic valve never touches it.
    Blobs,
}

impl CacheTier {
    /// Every tier, coarsest and most disposable first.
    pub const ALL: [Self; 4] = [
        Self::Targets,
        Self::Workspaces,
        Self::CargoHome,
        Self::Blobs,
    ];

    /// The directory name under the cache root.
    #[must_use]
    pub fn dir_name(self) -> &'static str {
        match self {
            Self::Targets => "targets",
            Self::Workspaces => "workspaces",
            Self::CargoHome => "cargo-home",
            Self::Blobs => "blobs",
        }
    }

    /// Whether the automatic pressure valve may clear this tier.
    ///
    /// [`Self::Blobs`] is excluded: the valve runs unattended at boot, and
    /// losing compiled output silently turns every subsequent page view into a
    /// cold compile. An administrator can still clear it deliberately.
    #[must_use]
    pub fn valve_may_clear(self) -> bool {
        !matches!(self, Self::Blobs)
    }

    /// Path of this tier under `cache_dir`.
    ///
    /// The reason tiers are an enum: a server fn taking a caller-supplied name
    /// and joining it onto the cache path is a directory traversal, and there
    /// is no value of this type that escapes `cache_dir`.
    #[must_use]
    pub fn path(self, cache_dir: &std::path::Path) -> std::path::PathBuf {
        cache_dir.join(self.dir_name())
    }
}

#[cfg(test)]
mod cell_type_tests {
    use super::CellType;

    #[test]
    fn known_types_round_trip() {
        for (ty, json) in [
            (CellType::Code, "\"Code\""),
            (CellType::Markdown, "\"Markdown\""),
            (CellType::Linux, "\"Linux\""),
        ] {
            assert_eq!(serde_json::to_string(&ty).unwrap(), json);
            assert_eq!(serde_json::from_str::<CellType>(json).unwrap(), ty);
        }
    }

    #[test]
    fn an_unknown_type_is_inert_rather_than_code() {
        // The PRD-0047 failure mode: an old client that treats an unfamiliar
        // cell as `Code` compiles it to the wrong target and fails
        // incomprehensibly. It must land on `Unsupported`, never the default.
        let parsed: CellType = serde_json::from_str("\"Wasi\"").unwrap();
        assert_eq!(parsed, CellType::Unsupported);
        assert_ne!(parsed, CellType::Code, "must not fall back to the default");
        assert!(!parsed.compiles(), "an unknown cell must never compile");
    }

    #[test]
    fn one_unknown_cell_does_not_fail_the_whole_notebook() {
        // Without `#[serde(other)]` this is a hard parse error and the reader
        // loses every other cell in the document, not just the new one.
        #[derive(serde::Deserialize)]
        struct Cell {
            cell_type: CellType,
        }
        let cells: Vec<Cell> = serde_json::from_str(
            r#"[{"cell_type":"Code"},{"cell_type":"FromTheFuture"},{"cell_type":"Markdown"}]"#,
        )
        .expect("a future cell type must not fail the parse");
        assert_eq!(cells.len(), 3);
        assert_eq!(cells[1].cell_type, CellType::Unsupported);
        assert_eq!(cells[2].cell_type, CellType::Markdown);
    }

    #[test]
    fn only_code_and_linux_compile() {
        assert!(CellType::Code.compiles());
        assert!(CellType::Linux.compiles());
        assert!(!CellType::Markdown.compiles());
        assert!(!CellType::Unsupported.compiles());
        assert!(CellType::Linux.is_linux());
        assert!(!CellType::Code.is_linux());
    }
}
