//! Shared types for the ironpad compilation pipeline, notebook persistence, and UI.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ── Compilation Types ────────────────────────────────────────────────────────

/// Request sent from the client to compile a single cell.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CompileRequest {
    pub notebook_id: String,
    pub cell_id: String,
    pub source: String,
    pub cargo_toml: String,
    /// Type tags from all previous cells, used to generate typed input bindings.
    #[serde(default)]
    pub previous_cell_types: Vec<Option<String>>,
    /// Notebook-level shared Cargo.toml whose dependencies are merged with per-cell deps.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_cargo_toml: Option<String>,
    /// Notebook-level shared Rust source included as `src/shared.rs` in every cell micro-crate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_source: Option<String>,
}

/// Response from the server after a compilation attempt.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CompileResponse {
    /// The compiled WASM blob (empty on failure).
    pub wasm_blob: Vec<u8>,
    /// Compiler diagnostics (errors, warnings, notes).
    pub diagnostics: Vec<Diagnostic>,
    /// Whether the result was served from cache.
    pub cached: bool,
    /// Number of scaffold preamble lines for diagnostic line-number adjustment.
    #[serde(default)]
    pub preamble_lines: u32,
    /// JS glue module generated by `wasm-bindgen` (ES module source).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub js_glue: Option<String>,
}

/// A single compiler diagnostic (error, warning, or note).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Diagnostic {
    pub message: String,
    pub severity: Severity,
    pub spans: Vec<Span>,
    /// Optional Rust error code (e.g. `"E0308"`), used for linking to the
    /// [Rust error index](https://doc.rust-lang.org/error_codes/).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

/// Severity level for a compiler diagnostic.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
    Note,
}

/// A source-code span associated with a diagnostic.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Span {
    pub line_start: u32,
    pub line_end: u32,
    pub col_start: u32,
    pub col_end: u32,
    pub label: Option<String>,
}

// ── Execution Result Types ───────────────────────────────────────────────────

/// Result of executing a compiled WASM cell.
///
/// Populated after the WASM executor runs `cell_main`.  Until execution is
/// wired up (T-036/T-037), the UI can still render this type when it becomes
/// available via the `CellOutputPanel`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ExecutionResult {
    /// JSON-serialized `Vec<DisplayPanel>` from the cell's output panels.
    /// Parse with `serde_json::from_str` on the frontend. Falls back to a single
    /// Text panel if parsing fails (backward compatibility).
    pub display_text: Option<String>,
    /// Raw output bytes (bincode-serialized payload for the next cell).
    pub output_bytes: Vec<u8>,
    /// Wall-clock execution time in milliseconds.
    pub execution_time_ms: f64,
    /// Rust type tag of the cell output (e.g. `"u32"`, `"String"`, `"Vec<i32>"`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub type_tag: Option<String>,
}

// ── Cell Type ────────────────────────────────────────────────────────────────

/// Distinguishes code cells (compiled to WASM) from markdown documentation cells.
#[derive(Clone, Debug, Serialize, Deserialize, Default, PartialEq)]
pub enum CellType {
    #[default]
    Code,
    Markdown,
}

// ── Cell Manifest ────────────────────────────────────────────────────────────

/// A single cell entry within a notebook manifest.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CellManifest {
    pub id: String,
    pub order: u32,
    pub label: String,
    /// Cell type — `Code` (default) or `Markdown`. Missing field deserializes as `Code`
    /// for backward compatibility with existing notebooks.
    #[serde(default)]
    pub cell_type: CellType,
}

// ── Self-contained Notebook Types ───────────────────────────────────────────

/// A complete, self-contained notebook with embedded cell content.
///
/// Carries everything needed to render or fork a notebook
/// in a single value. Used for IndexedDB storage and view-only/shared pages.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct IronpadNotebook {
    pub version: u32,
    pub id: Uuid,
    pub title: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_cargo_toml: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_source: Option<String>,
    pub cells: Vec<IronpadCell>,
}

impl IronpadNotebook {
    /// Creates a new empty notebook with the given title.
    pub fn new(title: &str) -> Self {
        let now = Utc::now();
        Self {
            version: 1,
            id: Uuid::new_v4(),
            title: title.to_string(),
            created_at: now,
            updated_at: now,
            shared_cargo_toml: None,
            shared_source: None,
            cells: Vec::new(),
        }
    }
}

/// A single cell within an [`IronpadNotebook`], including its source code.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct IronpadCell {
    pub id: String,
    pub order: u32,
    pub label: String,
    #[serde(default)]
    pub cell_type: CellType,
    pub source: String,
    /// Per-cell `Cargo.toml` content. `None` for Markdown cells.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cargo_toml: Option<String>,
}

// ── Public Notebook Types ───────────────────────────────────────────────────

/// Lightweight summary of a public notebook for the home-page listing.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PublicNotebookSummary {
    pub id: String,
    pub title: String,
    pub description: String,
    pub filename: String,
    pub cell_count: usize,
    #[serde(default)]
    pub tags: Vec<String>,
}

/// Index of all available public notebooks, loaded from `index.json`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PublicNotebookIndex {
    pub notebooks: Vec<PublicNotebookSummary>,
}
