//! Shared types for the ironpad compilation pipeline, notebook persistence, and UI.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ── Compilation Types ────────────────────────────────────────────────────────

/// Request sent from the client to compile a single cell.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CompileRequest {
    pub notebook_id: String,
    pub cell_id: String,
    pub source: String,
    pub cargo_toml: String,
    /// Type tags from all previous cells, used to generate typed input bindings.
    /// Empty string means the cell has no type tag (display-only output).
    #[serde(default)]
    pub previous_cell_types: Vec<String>,
    /// Notebook-level shared Cargo.toml whose dependencies are merged with per-cell deps.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_cargo_toml: Option<String>,
    /// Notebook-level shared Rust source included as `src/shared.rs` in every cell micro-crate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_source: Option<String>,
    /// When `true`, bypass the compilation cache and force a fresh build.
    #[serde(default)]
    pub force: bool,
}

/// Response from the server after a compilation attempt.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CompileResponse {
    /// The compiled WASM blob (empty on failure).
    pub wasm_blob: Vec<u8>,
    /// Compiler diagnostics (errors, warnings, notes).
    pub diagnostics: Vec<Diagnostic>,
    /// Whether the result was served from cache.
    pub cached: bool,
    /// Number of scaffold preamble lines for diagnostic line-number adjustment.
    #[serde(default)]
    pub preamble_lines: u32,
    /// JS glue module generated by `wasm-bindgen` (ES module source).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub js_glue: Option<String>,
}

/// A single compiler diagnostic (error, warning, or note).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Diagnostic {
    pub message: String,
    pub severity: Severity,
    pub spans: Vec<Span>,
    /// Optional Rust error code (e.g. `"E0308"`), used for linking to the
    /// [Rust error index](https://doc.rust-lang.org/error_codes/).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

/// Severity level for a compiler diagnostic.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
    Note,
}

/// A source-code span associated with a diagnostic.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Span {
    pub line_start: u32,
    pub line_end: u32,
    pub col_start: u32,
    pub col_end: u32,
    pub label: Option<String>,
}

// ── Execution Result Types ───────────────────────────────────────────────────

/// Result of executing a compiled WASM cell.
///
/// Populated after the WASM executor runs `cell_main`.  Until execution is
/// wired up (T-036/T-037), the UI can still render this type when it becomes
/// available via the `CellOutputPanel`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ExecutionResult {
    /// JSON-serialized `Vec<DisplayPanel>` from the cell's output panels.
    /// Parse with `serde_json::from_str` on the frontend. Falls back to a single
    /// Text panel if parsing fails (backward compatibility).
    pub display_text: Option<String>,
    /// Raw output bytes (bincode-serialized payload for the next cell).
    pub output_bytes: Vec<u8>,
    /// Wall-clock execution time in milliseconds.
    pub execution_time_ms: f64,
    /// Rust type tag of the cell output (e.g. `"u32"`, `"String"`, `"Vec<i32>"`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub type_tag: Option<String>,
    /// `true` when execution fell back to the main thread (e.g. because a
    /// DOM-dependent library like plotters panicked in the Web Worker).
    #[serde(default)]
    pub ran_on_main_thread: bool,
}

// ── Cell Type ────────────────────────────────────────────────────────────────

/// Distinguishes code cells (compiled to WASM) from markdown documentation cells.
#[derive(Clone, Debug, Serialize, Deserialize, Default, PartialEq)]
pub enum CellType {
    #[default]
    Code,
    Markdown,
}

// ── Cell Manifest ────────────────────────────────────────────────────────────

/// A single cell entry within a notebook manifest.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CellManifest {
    pub id: String,
    pub order: u32,
    pub label: String,
    /// Cell type — `Code` (default) or `Markdown`. Missing field deserializes as `Code`
    /// for backward compatibility with existing notebooks.
    #[serde(default)]
    pub cell_type: CellType,
}

// ── Self-contained Notebook Types ───────────────────────────────────────────

/// A complete, self-contained notebook with embedded cell content.
///
/// Carries everything needed to render or fork a notebook
/// in a single value. Used for `IndexedDB` storage and view-only/shared pages.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct IronpadNotebook {
    pub version: u32,
    pub id: Uuid,
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_cargo_toml: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared_source: Option<String>,
    /// When `true`, editing a cell auto-re-executes downstream cells after a debounce.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reactive_mode: Option<bool>,
    /// When `true`, view-only pages render code cells expanded (source
    /// visible) instead of collapsed — for notebooks where the code is the
    /// story, not just the machinery behind an output.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expand_code: Option<bool>,
    pub cells: Vec<IronpadCell>,
}

/// Default shared `Cargo.toml` for new notebooks. Provides `ironpad-cell`
/// and relaxed release-profile settings so cells compile quickly.
pub const DEFAULT_SHARED_CARGO_TOML: &str = "\
[dependencies]\n\
ironpad-cell = \"0.1\"\n\
\n\
[profile.release]\n\
opt-level = 1\n\
lto = false\n\
codegen-units = 16\n";

impl IronpadNotebook {
    /// Creates a new empty notebook with the given title.
    pub fn new(title: &str) -> Self {
        let now = Utc::now();
        Self {
            version: 1,
            id: Uuid::new_v4(),
            title: title.to_string(),
            description: None,
            tags: None,
            created_at: now,
            updated_at: now,
            shared_cargo_toml: Some(DEFAULT_SHARED_CARGO_TOML.to_string()),
            shared_source: None,
            reactive_mode: None,
            expand_code: None,
            cells: Vec::new(),
        }
    }
}

/// A single cell within an [`IronpadNotebook`], including its source code.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct IronpadCell {
    pub id: String,
    pub order: u32,
    pub label: String,
    #[serde(default)]
    pub cell_type: CellType,
    pub source: String,
    /// Per-cell `Cargo.toml` content. `None` for Markdown cells.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cargo_toml: Option<String>,
    /// Optimistic concurrency control version. Incremented on each mutation.
    /// Defaults to 0 for backward compatibility with existing notebooks.
    #[serde(default)]
    pub version: u64,
}

// ── Public Notebook Types ───────────────────────────────────────────────────

/// Lightweight summary of a public notebook for the home-page listing.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PublicNotebookSummary {
    pub id: String,
    pub title: String,
    pub description: String,
    pub filename: String,
    pub cell_count: usize,
    #[serde(default)]
    pub tags: Vec<String>,
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cell_without_version_field_defaults_to_zero() {
        // Simulates loading a notebook saved before the version field existed.
        let json = r#"{
            "id": "cell-1",
            "order": 0,
            "label": "Cell 1",
            "source": "42"
        }"#;
        let cell: IronpadCell = serde_json::from_str(json).unwrap();
        assert_eq!(cell.version, 0);
    }

    #[test]
    fn cell_with_version_field_round_trips() {
        let cell = IronpadCell {
            id: "cell-1".into(),
            order: 0,
            label: "Cell 1".into(),
            cell_type: CellType::Code,
            source: "42".into(),
            cargo_toml: None,
            version: 7,
        };
        let json = serde_json::to_string(&cell).unwrap();
        let back: IronpadCell = serde_json::from_str(&json).unwrap();
        assert_eq!(back.version, 7);
    }

    #[test]
    fn cell_version_zero_is_serialized() {
        let cell = IronpadCell {
            id: "cell-1".into(),
            order: 0,
            label: "Cell 1".into(),
            cell_type: CellType::Code,
            source: "42".into(),
            cargo_toml: None,
            version: 0,
        };
        let json = serde_json::to_string(&cell).unwrap();
        // version:0 should be present (not skipped).
        assert!(json.contains("\"version\":0"));
    }

    // ── reactive_mode field ────────────────────────────────────────────

    #[test]
    fn notebook_without_reactive_mode_defaults_to_none() {
        let json = r#"{
            "version": 1,
            "id": "00000000-0000-0000-0000-000000000001",
            "title": "Test",
            "created_at": "2025-01-01T00:00:00Z",
            "updated_at": "2025-01-01T00:00:00Z",
            "cells": []
        }"#;
        let nb: IronpadNotebook = serde_json::from_str(json).unwrap();
        assert_eq!(nb.reactive_mode, None);
    }

    #[test]
    fn notebook_with_reactive_mode_true_round_trips() {
        let mut nb = IronpadNotebook::new("Reactive");
        nb.reactive_mode = Some(true);
        let json = serde_json::to_string(&nb).unwrap();
        assert!(json.contains("\"reactive_mode\":true"));
        let back: IronpadNotebook = serde_json::from_str(&json).unwrap();
        assert_eq!(back.reactive_mode, Some(true));
    }

    #[test]
    fn notebook_with_reactive_mode_false_round_trips() {
        let mut nb = IronpadNotebook::new("Non-Reactive");
        nb.reactive_mode = Some(false);
        let json = serde_json::to_string(&nb).unwrap();
        assert!(json.contains("\"reactive_mode\":false"));
        let back: IronpadNotebook = serde_json::from_str(&json).unwrap();
        assert_eq!(back.reactive_mode, Some(false));
    }

    #[test]
    fn notebook_reactive_mode_none_is_omitted_from_json() {
        let nb = IronpadNotebook::new("Default");
        let json = serde_json::to_string(&nb).unwrap();
        assert!(
            !json.contains("reactive_mode"),
            "reactive_mode=None should be skipped"
        );
    }

    // ── expand_code field ──────────────────────────────────────────────

    #[test]
    fn notebook_without_expand_code_defaults_to_none() {
        let json = r#"{
            "version": 1,
            "id": "00000000-0000-0000-0000-000000000001",
            "title": "Test",
            "created_at": "2025-01-01T00:00:00Z",
            "updated_at": "2025-01-01T00:00:00Z",
            "cells": []
        }"#;
        let nb: IronpadNotebook = serde_json::from_str(json).unwrap();
        assert_eq!(nb.expand_code, None);
    }

    #[test]
    fn notebook_with_expand_code_true_round_trips() {
        let mut nb = IronpadNotebook::new("Code-Forward");
        nb.expand_code = Some(true);
        let json = serde_json::to_string(&nb).unwrap();
        assert!(json.contains("\"expand_code\":true"));
        let back: IronpadNotebook = serde_json::from_str(&json).unwrap();
        assert_eq!(back.expand_code, Some(true));
    }

    #[test]
    fn notebook_expand_code_none_is_omitted_from_json() {
        let nb = IronpadNotebook::new("Default");
        let json = serde_json::to_string(&nb).unwrap();
        assert!(
            !json.contains("expand_code"),
            "expand_code=None should be skipped"
        );
    }

    #[test]
    fn notebook_new_defaults_reactive_mode_to_none() {
        let nb = IronpadNotebook::new("Fresh");
        assert_eq!(nb.reactive_mode, None);
    }

    /// Verify every `.ironpad` file in `public/notebooks/` deserializes as a
    /// valid [`IronpadNotebook`] and that each cell satisfies basic invariants.
    ///
    /// This catches missing/mistyped fields early — before they reach the
    /// server's `get_public_notebook` endpoint and produce a runtime error.
    #[test]
    fn all_public_notebooks_conform_to_schema() {
        let workspace_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .expect("could not locate workspace root");
        let notebooks_dir = workspace_root.join("public").join("notebooks");

        // ── Validate each .ironpad file ──────────────────────────────
        let mut count = 0;
        for entry in std::fs::read_dir(&notebooks_dir).expect("cannot read notebooks dir") {
            let entry = entry.expect("bad dir entry");
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("ironpad") {
                continue;
            }
            let filename = path.file_name().unwrap().to_string_lossy().to_string();

            let bytes =
                std::fs::read(&path).unwrap_or_else(|e| panic!("cannot read {filename}: {e}"));
            let nb: IronpadNotebook = serde_json::from_slice(&bytes)
                .unwrap_or_else(|e| panic!("{filename}: schema error: {e}"));

            // version must be 1.
            assert_eq!(
                nb.version, 1,
                "{filename}: unexpected version {}",
                nb.version
            );

            // Must have at least one cell.
            assert!(!nb.cells.is_empty(), "{filename}: no cells");

            // Public notebooks must have a description.
            assert!(
                nb.description.is_some(),
                "{filename}: missing description field"
            );

            // Cell order values must be sequential starting at 0.
            for (i, cell) in nb.cells.iter().enumerate() {
                assert_eq!(
                    cell.order,
                    u32::try_from(i).expect("too many cells"),
                    "{filename}: cell[{i}] order is {} but expected {i}",
                    cell.order
                );
                assert!(!cell.id.is_empty(), "{filename}: cell[{i}] has empty id");
                assert!(
                    !cell.label.is_empty(),
                    "{filename}: cell[{i}] has empty label"
                );
                assert!(
                    !cell.source.is_empty(),
                    "{filename}: cell[{i}] has empty source"
                );
            }

            count += 1;
        }

        // Sanity: we validated at least one notebook.
        assert!(
            count > 0,
            "no .ironpad files found in {}",
            notebooks_dir.display()
        );
    }
}
